name = "untapped-table"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
